--------------------------------------------
 Lexema                        | Token
--------------------------------------------
 constantes                    | <PalRes>
 PI                            | <Ident>
 :=                            | <OpAsig>
 3.141593                      | <CteReal>
 ;                             | <Delim>
 MAX                           | <Ident>
 :=                            | <OpAsig>
 30                            | <CteEnt>
 ;                             | <Delim>
 variables                     | <PalRes>
 i                             | <Ident>
 ,                             | <Delim>
 j                             | <Ident>
 ,                             | <Delim>
 k                             | <Ident>
 ,                             | <Delim>
 n                             | <Ident>
 ,                             | <Delim>
 vector                        | <Ident>
 [                             | <Delim>
 MAX                           | <Ident>
 ]                             | <Delim>
 ,                             | <Delim>
 matriz                        | <Ident>
 [                             | <Delim>
 MAX                           | <Ident>
 ]                             | <Delim>
 [                             | <Delim>
 MAX                           | <Ident>
 ]                             | <Delim>
 :                             | <Delim>
 entero                        | <Tipo>
 ;                             | <Delim>
 r                             | <Ident>
 ,                             | <Delim>
 h                             | <Ident>
 ,                             | <Delim>
 s                             | <Ident>
 :=                            | <OpAsig>
 3                             | <CteEnt>
 :                             | <Delim>
 real                          | <Tipo>
 ;                             | <Delim>
 alfa                          | <Ident>
 ,                             | <Delim>
 beta                          | <Ident>
 :                             | <Delim>
 alfanumerico                  | <Tipo>
 ;                             | <Delim>
 log1                          | <Ident>
 ,                             | <Delim>
 log2                          | <Ident>
 :                             | <Delim>
 logico                        | <Tipo>
 ;                             | <Delim>
 programa                      | <PalRes>
 lee                           | <PalRes>
 (                             | <Delim>
 k                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 programa                      | <PalRes>
 .                             | <Delim>
