--------------------------------------------
 Lexema                        | Token
--------------------------------------------
 funcion                       | <PalRes>
 FacIter                       | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 :                             | <Delim>
 entero                        | <Tipo>
 inicio                        | <PalRes>
 Facto                         | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 ;                             | <Delim>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 n                             | <Ident>
 hasta                         | <PalRes>
 2                             | <CteEnt>
 incr                          | <PalRes>
 8                             | <CteEnt>
 Facto                         | <Ident>
 :=                            | <OpAsig>
 Facto                         | <Ident>
 *                             | <OpArit>
 i                             | <Ident>
 ;                             | <Delim>
 regresa                       | <PalRes>
 (                             | <Delim>
 facto                         | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 funcion                       | <PalRes>
 ;                             | <Delim>
 programa                      | <PalRes>
 limpia                        | <PalRes>
 ;                             | <Delim>
 k                             | <Ident>
 :=                            | <OpAsig>
 3                             | <CteEnt>
 ;                             | <Delim>
 llama                         | <PalRes>
 Selecciona                    | <Ident>
 (                             | <Delim>
 )                             | <Delim>
 ;                             | <Delim>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Dame tu nombre: "            | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 alfa                          | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Dame tu Apellido: "          | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 beta                          | <Ident>
 :=                            | <OpAsig>
 "Villalvazo"                  | <CteAlfa>
 ;                             | <Delim>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 beta                          | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 k                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 programa                      | <PalRes>
 .                             | <Delim>
