--------------------------------------------
 Lexema                        | Token
--------------------------------------------
 constantes                    | <PalRes>
 PI                            | <Ident>
 :=                            | <OpAsig>
 3.141592                      | <CteReal>
 ;                             | <Delim>
 MAX                           | <Ident>
 :=                            | <OpAsig>
 30                            | <CteEnt>
 ;                             | <Delim>
 variables                     | <PalRes>
 i                             | <Ident>
 ,                             | <Delim>
 j                             | <Ident>
 ,                             | <Delim>
 k                             | <Ident>
 ,                             | <Delim>
 n                             | <Ident>
 ,                             | <Delim>
 vector                        | <Ident>
 [                             | <Delim>
 MAX                           | <Ident>
 ]                             | <Delim>
 ,                             | <Delim>
 matriz                        | <Ident>
 [                             | <Delim>
 MAX                           | <Ident>
 ]                             | <Delim>
 [                             | <Delim>
 MAX                           | <Ident>
 ]                             | <Delim>
 :                             | <Delim>
 entero                        | <Tipo>
 ;                             | <Delim>
 r                             | <Ident>
 ,                             | <Delim>
 s                             | <Ident>
 ,                             | <Delim>
 t                             | <Ident>
 :                             | <Delim>
 real                          | <Tipo>
 ;                             | <Delim>
 Alfa                          | <Ident>
 ,                             | <Delim>
 Beta                          | <Ident>
 :                             | <Delim>
 alfanumerico                  | <Tipo>
 ;                             | <Delim>
 Log1                          | <Ident>
 ,                             | <Delim>
 Log2                          | <Ident>
 :                             | <Delim>
 logico                        | <Tipo>
 ;                             | <Delim>
 prot                          | <PalRes>
 funcion                       | <PalRes>
 FacRec                        | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 :                             | <Delim>
 entero                        | <Tipo>
 ;                             | <Delim>
 prot                          | <PalRes>
 funcion                       | <PalRes>
 FacIter                       | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 :                             | <Delim>
 entero                        | <Tipo>
 ;                             | <Delim>
 prot                          | <PalRes>
 procedimiento                 | <PalRes>
 leeVec                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 ;                             | <Delim>
 prot                          | <PalRes>
 procedimiento                 | <PalRes>
 leeMat                        | <Ident>
 (                             | <Delim>
 K                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 ;                             | <Delim>
 prot                          | <PalRes>
 procedimiento                 | <PalRes>
 OrdVec                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 ;                             | <Delim>
 prot                          | <PalRes>
 procedimiento                 | <PalRes>
 ImpMat                        | <Ident>
 (                             | <Delim>
 K                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 ;                             | <Delim>
 prot                          | <PalRes>
 procedimiento                 | <PalRes>
 MulMat                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 ,                             | <Delim>
 v                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 Selecciona                    | <Ident>
 (                             | <Delim>
 )                             | <Delim>
 inicio                        | <PalRes>
 repetir                       | <PalRes>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Dame un numero: "            | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Factorial R]recursivo I]interactivo S]salir: "| <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 opc                           | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 cuando                        | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 del                           | <Ident>
 opc                           | <Ident>
 inicio                        | <PalRes>
 sea                           | <PalRes>
 "R"                           | <CteAlfa>
 ,                             | <Delim>
 "r"                           | <CteAlfa>
 :                             | <Delim>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "Factorial Recursivo de "     | <CteAlfa>
 ,                             | <Delim>
 n                             | <Ident>
 ,                             | <Delim>
 " es= "                       | <CteAlfa>
 )                             | <Delim>
 sea                           | <PalRes>
 "I"                           | <CteAlfa>
 ,                             | <Delim>
 "i"                           | <CteAlfa>
 :                             | <Delim>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "Factorial Iterativo de "     | <CteAlfa>
 ,                             | <Delim>
 n                             | <Ident>
 ,                             | <Delim>
 " es= "                       | <CteAlfa>
 )                             | <Delim>
 otro                          | <PalRes>
 :                             | <Delim>
 si                            | <PalRes>
 (                             | <Delim>
 opc                           | <Ident>
 <>                            | <OpRel>
 "S"                           | <CteAlfa>
 y                             | <OpLog>
 opc                           | <Ident>
 <>                            | <OpRel>
 "s"                           | <CteAlfa>
 )                             | <Delim>
 hacer                         | <PalRes>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "Opcion Invalida!!!"          | <CteAlfa>
 )                             | <Delim>
 fin                           | <PalRes>
 ;                             | <Delim>
 hasta                         | <PalRes>
 que                           | <PalRes>
 (                             | <Delim>
 opc                           | <Ident>
 =                             | <OpRel>
 "S"                           | <CteAlfa>
 o                             | <OpLog>
 opc                           | <Ident>
 =                             | <OpRel>
 "s"                           | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 funcion                       | <PalRes>
 FacRec                        | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 :                             | <Delim>
 entero                        | <Tipo>
 inicio                        | <PalRes>
 si                            | <PalRes>
 (                             | <Delim>
 n                             | <Ident>
 <                             | <OpRel>
 2                             | <CteEnt>
 )                             | <Delim>
 hacer                         | <PalRes>
 regresa                       | <PalRes>
 (                             | <Delim>
 1                             | <CteEnt>
 )                             | <Delim>
 sino                          | <PalRes>
 regresa                       | <PalRes>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 funcion                       | <PalRes>
 ;                             | <Delim>
 funcion                       | <PalRes>
 FacIter                       | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 :                             | <Delim>
 entero                        | <Tipo>
 variables                     | <PalRes>
 Facto                         | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 ;                             | <Delim>
 inicio                        | <PalRes>
 Facto                         | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 ;                             | <Delim>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 n                             | <Ident>
 hasta                         | <PalRes>
 2                             | <CteEnt>
 decr                          | <PalRes>
 1                             | <CteEnt>
 Facto                         | <Ident>
 :=                            | <OpAsig>
 Facto                         | <Ident>
 *                             | <OpArit>
 i                             | <Ident>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 funcion                       | <PalRes>
 ;                             | <Delim>
 funcion                       | <PalRes>
 VolCil                        | <Ident>
 (                             | <Delim>
 radio                         | <Ident>
 ,                             | <Delim>
 altura                        | <Ident>
 :                             | <Delim>
 real                          | <Tipo>
 )                             | <Delim>
 :                             | <Delim>
 real                          | <Tipo>
 inicio                        | <PalRes>
 regresa                       | <PalRes>
 (                             | <Delim>
 PI                            | <Ident>
 *                             | <OpArit>
 radio                         | <Ident>
 ^                             | <OpArit>
 2                             | <CteEnt>
 *                             | <OpArit>
 altura                        | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 funcion                       | <PalRes>
 ;                             | <Delim>
 funcion                       | <PalRes>
 Concat                        | <Ident>
 (                             | <Delim>
 a                             | <Ident>
 ,                             | <Delim>
 b                             | <Ident>
 :                             | <Delim>
 alfanumerico                  | <Tipo>
 )                             | <Delim>
 :                             | <Delim>
 alfanumerico                  | <Tipo>
 inicio                        | <PalRes>
 regresa                       | <PalRes>
 (                             | <Delim>
 a                             | <Ident>
 +                             | <OpArit>
 " "                           | <CteAlfa>
 +                             | <OpArit>
 b                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 funcion                       | <PalRes>
 ;                             | <Delim>
 funcion                       | <PalRes>
 Compara                       | <Ident>
 (                             | <Delim>
 a                             | <Ident>
 ,                             | <Delim>
 b                             | <Ident>
 :                             | <Delim>
 real                          | <Tipo>
 ;                             | <Delim>
 opc                           | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 :                             | <Delim>
 logico                        | <Tipo>
 inicio                        | <PalRes>
 si                            | <PalRes>
 (                             | <Delim>
 opc                           | <Ident>
 =                             | <OpRel>
 1                             | <CteEnt>
 )                             | <Delim>
 hacer                         | <PalRes>
 regresa                       | <PalRes>
 (                             | <Delim>
 a                             | <Ident>
 <                             | <OpRel>
 b                             | <Ident>
 )                             | <Delim>
 sino                          | <PalRes>
 si                            | <PalRes>
 (                             | <Delim>
 opc                           | <Ident>
 =                             | <OpRel>
 2                             | <CteEnt>
 )                             | <Delim>
 hacer                         | <PalRes>
 regresa                       | <PalRes>
 (                             | <Delim>
 a                             | <Ident>
 >                             | <OpRel>
 b                             | <Ident>
 )                             | <Delim>
 sino                          | <PalRes>
 si                            | <PalRes>
 (                             | <Delim>
 opc                           | <Ident>
 =                             | <OpRel>
 3                             | <CteEnt>
 )                             | <Delim>
 hacer                         | <PalRes>
 regresa                       | <PalRes>
 (                             | <Delim>
 a                             | <Ident>
 =                             | <OpRel>
 b                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 funcion                       | <PalRes>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 leeVecMat                     | <Ident>
 (                             | <Delim>
 )                             | <Delim>
 inicio                        | <PalRes>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Dame elementos de Vector( N ) o Grado de Matriz( NxN ): "| <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 llama                         | <PalRes>
 leeVec                        | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 llama                         | <PalRes>
 OrdVec                        | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 llama                         | <PalRes>
 Impvec                        | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 llama                         | <PalRes>
 leeMat                        | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 llama                         | <PalRes>
 MulMat                        | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 llama                         | <PalRes>
 ImpMat                        | <Ident>
 (                             | <Delim>
 n                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 Test                          | <Ident>
 (                             | <Delim>
 )                             | <Delim>
 inicio                        | <PalRes>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 10                            | <CteEnt>
 inicio                        | <PalRes>
 si                            | <PalRes>
 (                             | <Delim>
 i                             | <Ident>
 =                             | <OpRel>
 5                             | <CteEnt>
 )                             | <Delim>
 hacer                         | <PalRes>
 continua                      | <PalRes>
 ;                             | <Delim>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "i= "                         | <CteAlfa>
 ,                             | <Delim>
 i                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 ;                             | <Delim>
 i                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 ;                             | <Delim>
 repetir                       | <PalRes>
 si                            | <PalRes>
 (                             | <Delim>
 i                             | <Ident>
 =                             | <OpRel>
 7                             | <CteEnt>
 )                             | <Delim>
 hacer                         | <PalRes>
 interrumpe                    | <PalRes>
 ;                             | <Delim>
 hasta                         | <PalRes>
 que                           | <PalRes>
 (                             | <Delim>
 i                             | <Ident>
 =                             | <OpRel>
 10                            | <CteEnt>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 leeVec                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 inicio                        | <PalRes>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 n                             | <Ident>
 inicio                        | <PalRes>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Vector["                     | <CteAlfa>
 ,                             | <Delim>
 i                             | <Ident>
 ,                             | <Delim>
 "]: "                         | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 Vector                        | <Ident>
 [                             | <Delim>
 i                             | <Ident>
 ]                             | <Delim>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 OrdVec                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 variables                     | <PalRes>
 Temp                          | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 ;                             | <Delim>
 inicio                        | <PalRes>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 (                             | <Delim>
 k                             | <Ident>
 -                             | <OpArit>
 1                             | <CteEnt>
 )                             | <Delim>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 j                             | <Ident>
 :=                            | <OpAsig>
 i                             | <Ident>
 +                             | <OpArit>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 k                             | <Ident>
 si                            | <PalRes>
 (                             | <Delim>
 i                             | <Ident>
 )                             | <Delim>
 hacer                         | <PalRes>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 ImpVec                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 inicio                        | <PalRes>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 k                             | <Ident>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "Vector["                     | <CteAlfa>
 ,                             | <Delim>
 i                             | <Ident>
 ,                             | <Delim>
 "]= "                         | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 leeMat                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 inicio                        | <PalRes>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 n                             | <Ident>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 j                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 n                             | <Ident>
 inicio                        | <PalRes>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Matriz["                     | <CteAlfa>
 ,                             | <Delim>
 i                             | <Ident>
 ,                             | <Delim>
 "]["                          | <CteAlfa>
 ,                             | <Delim>
 j                             | <Ident>
 ,                             | <Delim>
 "]: "                         | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 Matriz                        | <Ident>
 [                             | <Delim>
 i                             | <Ident>
 ]                             | <Delim>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 MulMat                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 ,                             | <Delim>
 v                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 inicio                        | <PalRes>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 k                             | <Ident>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 j                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 k                             | <Ident>
 Matriz                        | <Ident>
 [                             | <Delim>
 i                             | <Ident>
 ]                             | <Delim>
 :=                            | <OpAsig>
 v                             | <Ident>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 procedimiento                 | <PalRes>
 ImpMat                        | <Ident>
 (                             | <Delim>
 k                             | <Ident>
 :                             | <Delim>
 entero                        | <Tipo>
 )                             | <Delim>
 inicio                        | <PalRes>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 i                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 k                             | <Ident>
 desde                         | <PalRes>
 el                            | <PalRes>
 valor                         | <PalRes>
 de                            | <PalRes>
 j                             | <Ident>
 :=                            | <OpAsig>
 1                             | <CteEnt>
 hasta                         | <PalRes>
 k                             | <Ident>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "Matriz["                     | <CteAlfa>
 ,                             | <Delim>
 i                             | <Ident>
 ,                             | <Delim>
 "]["                          | <CteAlfa>
 ,                             | <Delim>
 j                             | <Ident>
 ,                             | <Delim>
 "]= "                         | <CteAlfa>
 ,                             | <Delim>
 Matriz                        | <Ident>
 [                             | <Delim>
 i                             | <Ident>
 ]                             | <Delim>
 [                             | <Delim>
 j                             | <Ident>
 ]                             | <Delim>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 procedimiento                 | <PalRes>
 ;                             | <Delim>
 programa                      | <PalRes>
 limpia                        | <PalRes>
 ;                             | <Delim>
 Selecciona                    | <Ident>
 (                             | <Delim>
 )                             | <Delim>
 ;                             | <Delim>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Dame Radio = "               | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 r                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Dame Altura= "               | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 s                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "El Volum del Cilindro= "     | <CteAlfa>
 ,                             | <Delim>
 VolCil                        | <Ident>
 (                             | <Delim>
 r                             | <Ident>
 ,                             | <Delim>
 s                             | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "Es el radio= "               | <CteAlfa>
 ,                             | <Delim>
 r                             | <Ident>
 ,                             | <Delim>
 " mayor que Altura= "         | <CteAlfa>
 ,                             | <Delim>
 s                             | <Ident>
 ,                             | <Delim>
 " ? "                         | <CteAlfa>
 ,                             | <Delim>
 Compara                       | <Ident>
 (                             | <Delim>
 r                             | <Ident>
 ,                             | <Delim>
 s                             | <Ident>
 ,                             | <Delim>
 2                             | <CteEnt>
 )                             | <Delim>
 )                             | <Delim>
 ;                             | <Delim>
 leeVecmat                     | <Ident>
 (                             | <Delim>
 )                             | <Delim>
 ;                             | <Delim>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Dame tu nombre: "            | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 alfa                          | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 imprime                       | <PalRes>
 (                             | <Delim>
 "Dame tu Apellido: "          | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 lee                           | <PalRes>
 (                             | <Delim>
 beta                          | <Ident>
 )                             | <Delim>
 ;                             | <Delim>
 imprimenl                     | <PalRes>
 (                             | <Delim>
 "Hola "                       | <CteAlfa>
 ,                             | <Delim>
 Concat                        | <Ident>
 (                             | <Delim>
 alfa                          | <Ident>
 ,                             | <Delim>
 beta                          | <Ident>
 )                             | <Delim>
 ,                             | <Delim>
 " ya la pasaste!!!"           | <CteAlfa>
 )                             | <Delim>
 ;                             | <Delim>
 fin                           | <PalRes>
 de                            | <PalRes>
 programa                      | <PalRes>
 .                             | <Delim>
